### ISSUE TITLE
Testo Esercizi

### ISSUE THREAD

**Issue by korsmakolnikov** [CodeGardenRome/incremental-katas-jvm-langs#8]
Non c'è più il testo dei kata nel repo. Io ho solo il kata zero nella directory php.

**edit**: ok è un po' sparso tra la la directory java e quella php. Magari metterlo tutto in una cartella nella root?

**Comment by vitalijzad** [comment]
Sono decisamente a favore!

**Comment by korsmakolnikov** [comment]
poi lo sistemo allora.
